### PR TITLE
Pcl building

### PR DESCRIPTION
**Pull request by fmrico**
PCL and dependencies compilation for future pcl_ros (among others) compilation.

### CODE REVIEW

**Comment by esteve** [comment]
@fmrico I've changed the flann script to use the upstream repo, there was a typo in `-DBUILD_TESTS=OFF` that caused CMake to build the tests anyway (https://github.com/esteve/ros2_pepper/pull/9/commits/39026063afd617bd40c08a9cf28f8ad8eb8b0a1d)

**Comment by fmrico** [comment]
Excellent!!!:)

**Comment by fmrico** [comment]
Ready to merge?

**Comment by esteve** [comment]
@fmrico not yet, I think neither PCL or QHull need to be forked. I'm going to cherry-pick `flann` and merge PCL and QHull separately.

**Comment by esteve** [comment]
@fmrico I've pushed https://github.com/esteve/ros2_pepper/tree/qhull separately which uses https://github.com/qhull/qhull/commit/5a79a0009454c86e9848646b3c296009125231bf instead of `master`. I believe it's the same release as the Debian package for PCL depends on (i.e. QHull as a shared library)

**Comment by esteve** [comment]
@fmrico I've pushed a couple of changes to your branch. I've unforked QHull and PCL so that upstream sources are used instead. I've built all this locally, but just to make sure, could you build it too? Thanks.

**Comment by fmrico** [comment]
I have a couple of changes in pcl build script:
- Eigen include path was not correctly detected.
- QHull library was automatically (wrongly) detected as liblibqhull.so, instead of libqhull

Fixed in 11304d9

**Comment by esteve** [comment]
@fmrico could you paste here the error you had? It's weird, but this is I what I got before your changes:

```
....
-- Checking for module 'eigen3'
--   No package 'eigen3' found
-- Eigen found (include: /home/nao/ctc/eigen3/include/eigen3, version: 3.1.4)
-- FLANN found (include: /home/nao/.ros-root/ros1_dependencies/include, lib: optimized;/home/nao/.ros-root/ros1_dependencies/lib/libflann_cpp.so;debug;/home/nao/.ros-root/ros1_dependencies/lib/libflann_cpp.so)
-- Could NOT find LIBUSB_1 (missing:  LIBUSB_1_LIBRARY LIBUSB_1_INCLUDE_DIR)
-- Checking for module 'metslib'
--   No package 'metslib' found
-- QHULL found (include: /home/nao/.ros-root/ros1_dependencies/include, lib: optimized;/home/nao/.ros-root/ros1_dependencies/lib/libqhull_p.so;debug;/home/nao/.ros-root/ros1_dependencies/lib/libqhull_p.so)
...
```

CMake found both Eigen and QHull properly already. Moreover, PCL uses `EIGEN_ROOT` as a hint to find Eigen's path (see https://github.com/PointCloudLibrary/pcl/blob/master/cmake/Modules/FindEigen.cmake#L23)

**Comment by fmrico** [comment]
@esteve It's a bit strange, but I've reversed the changes of the last commit to show you the errors, I've cleaned everything to restart the process and now it finds everything perfectly, and not Sunday. I'm going to reverse the change, but let's keep this in mind in the future in case it reappears.

Reverted in 1d2de50

**Comment by esteve** [comment]
@fmrico I just merged it, thanks!

**Pull request merged**
