### PR TITLE
Optimized docker image.

### PR DESCRIPTION
**Pull request by TVerloop**
- ~~CTC is now embedded in the docker image.~~
 - RUN tags in docker are (as much as i saw fit) merged so that docker does not create more cache images than possible.
 - Unnecessary redefinition's of environmental variables and some volume linking are removed

### CODE REVIEW

**Comment by esteve** [comment]
Thanks, but I'd rather not include the CTC inside the image. If anyone wants to redistribute the image (e.g. put it up on Dockerhub), there may be issues with the copyright of the CTC.

**Comment by TVerloop** [comment]
Had not considered that. Reverted that. Also set the key-server back to the one you want. Keep accidentally pushing the one i use (corporate firewalls and what not.)

**Review by esteve — CHANGES_REQUESTED** [review]

**Comment by TVerloop** [comment]
Does this addition still have a point? Or shall we just close it?

**Comment by esteve** [comment]
@TVerloop I reviewed this PR a while ago, but I just realized that the comment I left weren't visible. Whatever you prefer, we can close it or you plan to work on it, I'm happy to keep it open.

**Comment by TVerloop** [comment]
@esteve I afraid i can not continue working on this project. I am about to graduate and after that i won't even have access to a pepper robot anymore.

**Comment by esteve** [comment]
@TVerloop no worries, thank you so much for all the hard work!

**Pull request closed without merging**
